### ISSUE TITLE
The anchor tag keeps showing up in places it shouldn't.

### ISSUE THREAD

**Issue by zubairabid** [zubairabid/ECell_build1#15]
![image](https://user-images.githubusercontent.com/26400677/40281967-4cc0cc0a-5c85-11e8-9667-b479265f5e30.png)

Visible in the image above. Can also be observed on viewing page source. @darthgera123 .

**Comment by darthgera123** [comment]
im supposed to remove 'welcome to jekyll' ?

**Comment by zubairabid** [comment]
Yeah. From the places where it isn't supposed to appear but randomly is.

**Comment by abhigyanghosh30** [comment]
close this issue?
