### ISSUE TITLE
Separation of concerns of events and blog posts.

### ISSUE THREAD

**Issue by zubairabid** [zubairabid/ECell_build1#45]
Very important.
Such that, on clicking "next post" in an event post, only events show up. Likewise with blog posts.

**Comment by darthgera123** [comment]
ive reverted back
and im creating an altogether section for blogs

**Comment by abhigyanghosh30** [comment]
I think I can fix the initial issue,should I try it or leave it?

**Comment by zubairabid** [comment]
Yeah, go ahead.

**Comment by darthgera123** [comment]
#73 completed

**Comment by abhigyanghosh30** [comment]
clarify a doubt please. What exactly is the difference between a blog post and an event post?

**Comment by abhigyanghosh30** [comment]
https://ajclarkson.co.uk/blog/jekyll-category-post-navigation/
solution is here

**Comment by abhigyanghosh30** [comment]
Fixed. Close this issue?
