### ISSUE TITLE
Blog page and individual layouts

### ISSUE THREAD

**Issue by zubairabid** [zubairabid/ECell_build1#83]

**Comment by zubairabid** [comment]
Tick them off as you're done
- [ ] Pagination
- [ ] Fixing the previous/next page links
- [ ] Explaining the facebook comments bit

**Comment by darthgera123** [comment]
what about facebook comments?

**Comment by zubairabid** [comment]
It's great rn, keep me updated. Also text when you comment, github doesn't seem to be giving notifications
