### ISSUE TITLE
Figuring out a theme (design, layout) for the website

### ISSUE THREAD

**Issue by zubairabid** [zubairabid/ECell_build1#9]
As the title suggests, we don't have a theme.

Or a consistent design guide.
Or anything that'll contribute to meaningful progress rn.

Currently, Abhigyan's footer is based on the previous website and the header is a generic.

I think it's best to figure out a consistent design first, then start on anything. Because otherwise we'll end up wasting time redoing many components.

@darthgera123 @abhigyanghosh30 please comment below so I know you're with me on this.

**Comment by zubairabid** [comment]
Review colour scheme please, especially links right now.

**Comment by darthgera123** [comment]
regarding the design i think we can for now have the design structure similar to the previous website and then see what works and what not

**Comment by zubairabid** [comment]
Looking good. Keeping with current, up for last minute changes

**Comment by zubairabid** [comment]
good. Look at the chrome desktop thing tho
